import assert from 'node:assert/strict';
import fs from 'node:fs';
const base='http://127.0.0.1:5173';
const password=process.env.TEST_ADMIN_PASSWORD||fs.readFileSync('.dev.vars','utf8').match(/^ADMIN_PASSWORD=([a-f0-9]{64})$/m)?.[1];
assert(password,'Local test password configured');
const signin=await fetch(base+'/api/auth',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({action:'login',password})});
assert.equal(signin.status,200);
const cookie=signin.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
assert(cookie,'Local sign in returns a session');
async function call(body,auth=false,action='public',extra={}){const r=await fetch(base+'/api?action='+action,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(auth?{cookie}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text);}catch{data={error:text};}return {status:r.status,data};}
assert.equal((await call(undefined,false,'admin')).status,403);
assert.equal((await call({action:'availability',date:'2026-11-01',from:'10:00',to:'12:00'})).status,403);
assert.equal((await call({action:'initialize'},true)).status,200);
assert.equal((await call({action:'initialize'},true,'public',{origin:'https://example.org'})).status,403);
const day=new Date(Date.now()+5*86400000).toISOString().slice(0,10);
assert.equal((await call({action:'availability',date:day,from:'10:00',to:'14:00'},true)).status,200);
assert.equal((await call({action:'availability',date:day,from:'11:00',to:'13:00'},true)).status,409);
const state=(await call()).data;
assert(state.slots.signature.length>0);
const start=state.slots.signature.find(t=>new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(t)===day);
assert(start,'Test day has a slot');
const payload={action:'book',serviceId:'signature',quotedPrice:2500,quotedDuration:45,quotedCurrency:'CAD',start,name:'QA Client',email:'qa@example.test',phone:'555-010-1234',note:'Local automated test'};
assert.equal((await call({...payload,quotedPrice:1})).status,409,'Changed prices require review');
const attempts=await Promise.all(Array.from({length:5},()=>call(payload)));
assert.equal(attempts.filter(r=>r.status===201).length,1,'Exactly one simultaneous booking succeeds');
assert.equal(attempts.filter(r=>r.status===409).length,4);
const booked=attempts.find(r=>r.status===201).data;
const after=(await call()).data;
assert(!after.slots.signature.includes(start));
assert(!after.slots.beard.includes(start+15*60000),'Different service cannot overlap');
assert(after.slots.beard.includes(start+45*60000),'Adjacent appointment stays available');
const admin=(await call(undefined,true,'admin')).data;
const window=admin.availability.find(w=>w.start<=start&&w.end>start);
assert.equal((await call({action:'removeAvailability',id:window.id},true)).status,409);
assert.equal((await call({...payload,start:start+60000})).status,409,'Off-grid starts rejected');
assert.equal((await call({...payload,start:Date.now()-3600000})).status,400);
assert.equal((await call({action:'manage',token:'x'.repeat(72)})).status,404);
assert.equal((await call({action:'manage',token:booked.token})).data.id,booked.id);
assert.equal((await call({action:'cancel',token:booked.token})).data.status,'cancelled');
assert((await call()).data.slots.signature.includes(start),'Cancellation releases time');
const again=await call({...payload,name:'QA Client Two'});
assert.equal(again.status,201,'Released time can be booked again');
const settings={...admin.settings,cancellationHours:168,currency:'USD',timezone:'Europe/London',location:'Changed location'};
assert.equal((await call({action:'settings',settings},true)).status,200);
assert.equal((await call({action:'manage',token:again.data.token})).data.settings.currency,admin.settings.currency,'Booked currency stays unchanged');
assert.equal((await call({action:'manage',token:again.data.token})).data.settings.location,admin.settings.location,'Booked location stays unchanged');
assert.equal((await call({action:'cancel',token:again.data.token})).status,409,'Cancellation cutoff enforced');
assert.equal((await call({action:'cancelAdmin',id:again.data.id},true)).status,200);
assert.equal((await call({action:'settings',settings:admin.settings},true)).status,200);
assert.equal((await call({action:'removeAvailability',id:window.id},true)).status,200);
const service={...admin.services[0],id:'qa-hidden',name:'QA Hidden',active:0};
assert.equal((await call({action:'service',service},true)).status,200);
assert(!(await call()).data.services.some(s=>s.id==='qa-hidden'));
assert.equal((await call({...payload,serviceId:'qa-hidden'})).status,409);
console.log('PASS: authorization, origin checks, availability, overlap validation, five concurrent clients, cross-service overlap, adjacency, off-grid/past rejection, private booking access, cancellation/rebooking, cutoff, admin cancellation, service visibility.');


