'use client';
import { useEffect, useState, useCallback, type FormEvent } from 'react';
import { Scissors, ArrowUpRight, ArrowRight, Check, Clock3, CalendarDays, MapPin, ChevronLeft, ChevronRight, Menu, X, Plus, Trash2, LogOut, Settings2, ShieldCheck, Download, Copy, CheckCircle2 } from 'lucide-react';
import { defaults, sampleServices, dayKey, type Settings, type Service } from '../lib/scheduling';
function Instagram({size=20}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>;}
type Booking={currency?:string;id:string;token?:string;service_name:string;price:number;start:number;end:number;name:string;status:string;settings:Settings;email?:string;phone?:string;note?:string};
type PublicData={settings:Settings;services:Service[];slots:Record<string,number[]>;isOwner:boolean};
type AdminData={settings:Settings;services:Service[];availability:{id:string;start:number;end:number}[];bookings:Booking[]};
async function api(body?:unknown,action='public'){const r=await fetch('/api?action='+action,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Unable to connect. Please try again.');return d;}
function price(n:number,currency:string){return new Intl.NumberFormat('en-CA',{style:'currency',currency,maximumFractionDigits:n%100?2:0}).format(n/100);}
function time(n:number,z:string){return new Intl.DateTimeFormat('en-CA',{timeZone:z,hour:'numeric',minute:'2-digit'}).format(n);}
function date(n:number,z:string){return new Intl.DateTimeFormat('en-CA',{timeZone:z,weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(n);}
function download(name:string,body:string,type:string){const u=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function calendar(b:Booking){const stamp=(n:number)=>new Date(n).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,'\\$&');download('joesblendz-appointment.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Joesblendz//Bookings//EN','BEGIN:VEVENT','UID:'+b.id+'@joesblendz','DTSTAMP:'+stamp(Date.now()),'DTSTART:'+stamp(b.start),'DTEND:'+stamp(b.end),'SUMMARY:'+esc('Joesblendz — '+b.service_name),'LOCATION:'+esc(b.settings.location),'DESCRIPTION:'+esc('Your appointment with Joesblendz. '+b.settings.contact),'END:VEVENT','END:VCALENDAR'].join('\r\n')+'\r\n','text/calendar');}
export default function JoeCuts({initialAdmin=false}:{initialAdmin?:boolean}){
 const [data,setData]=useState<PublicData>({settings:defaults,services:sampleServices,slots:{},isOwner:false});
 const [loaded,setLoaded]=useState(false),[error,setError]=useState(''),[admin,setAdmin]=useState(initialAdmin),[manage,setManage]=useState(''),[nav,setNav]=useState(false);
 const refresh=useCallback(async()=>{try{setData(await api());setLoaded(true);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{setAdmin(initialAdmin || new URLSearchParams(location.search).has('admin'));setManage(new URLSearchParams(location.hash.slice(1)).get('booking')||'');if(initialAdmin)return;refresh();const t=setInterval(refresh,15000);return()=>clearInterval(t);},[refresh,initialAdmin]);
 return <>
 <header className="site-header"><a className="brand" href="/" aria-label="Joesblendz home"><span className="brand-icon"><Scissors size={22}/></span>JOESBLENDZ</a><nav className={nav?'nav open':'nav'}><a href="/#services" onClick={()=>setNav(false)}>The services</a><a href="/#how" onClick={()=>setNav(false)}>How it works</a><a href="/#visit" onClick={()=>setNav(false)}>Good to know</a><a className="nav-instagram" href="https://www.instagram.com/joesblendz/" target="_blank" rel="noopener noreferrer"><Instagram size={16}/> @joesblendz</a></nav><a className="button small" href="/#book">Book a cut <ArrowUpRight size={16}/></a><button className="mobile-menu icon-button" aria-label="Toggle navigation" onClick={()=>setNav(!nav)}>{nav?<X/>:<Menu/>}</button></header>
 {process.env.NODE_ENV==='development'&&<div className="preview-banner">LOCAL PREVIEW · Test availability only. No real appointments or messages.</div>}
 {error&&<div className="notice error" role="alert">{error} <button onClick={refresh}>Try again</button></div>}
 {admin?<Admin onChange={refresh}/>:manage?<Manage token={manage} onChange={refresh}/>:<>
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> YOUR NEXT FRESH START</div><h1>A fresh cut.<br/>On <em>your</em> time.</h1><p>Good hair. No back-and-forth.<br/>Find an opening, take a seat, leave looking sharp.</p><a href="#book" className="button primary">Find your time <ArrowUpRight size={19}/></a><a className="instagram-hero" href="https://www.instagram.com/joesblendz/" target="_blank" rel="noopener noreferrer"><Instagram size={18}/><span>See the cuts. DM for questions.<b>@joesblendz <ArrowUpRight size={14}/></b></span></a><div className="hero-note"><Clock3 size={15}/> By appointment. Always worth making time for.</div></div>
 <div className="hero-art" aria-label="Joesblendz illustrated barber poster"><div className="poster-top"><span>THE CHAIR IS YOURS.</span><span>JOES / BLENDZ</span></div><div className="poster-circle"/><div className="poster-type">STAY<br/><i>SHARP.</i></div><svg className="scissor-art" viewBox="0 0 360 320" aria-hidden="true"><g fill="none" stroke="#e8ddc8" strokeWidth="15" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="92" cy="235" rx="37" ry="43" transform="rotate(28 92 235)"/><ellipse cx="196" cy="261" rx="37" ry="43" transform="rotate(-15 196 261)"/><path d="M111 198L243 26Q259 93 179 183L181 219M171 224L117 38Q176 82 177 157L111 198"/></g><circle cx="162" cy="171" r="12" fill="#ec7147" stroke="#17372e" strokeWidth="4"/></svg><div className="poster-bottom"><span>A LITTLE TIME.<br/>A WHOLE NEW FEELING.</span><span className="poster-seal">JB<span>BARBERING</span></span></div></div>
 </section>
 <div className="ticker" aria-hidden="true"><span>FRESH CUTS</span><Scissors size={19}/><span>CLEAN LINES</span><Scissors size={19}/><span>YOUR KIND OF STYLE</span><Scissors size={19}/><span>JOESBLENDZ</span><Scissors size={19}/></div>
 <section id="services" className="wrap services-section"><div className="section-heading"><div><div className="eyebrow">01 / THE MENU</div><h2>Keep it fresh.</h2></div><p>A little maintenance. A big difference.<br/>Pick the service that feels like you.</p></div>{data.settings.sample&&<div className="sample-note">Preview menu · sample services and prices, editable by Joe.</div>}<div className="service-grid">{data.services.map((s,i)=><a key={s.id} href={'#book'} className="service-card" onClick={()=>window.dispatchEvent(new CustomEvent('choose-service',{detail:s.id}))}><div className="service-top"><span className="service-number">0{i+1}</span>{i===0?<Scissors size={28}/>:i===1?<span className="beard-icon">⌁</span>:<span className="star-icon">✳</span>}</div><h3>{s.name}</h3><p>{s.description}</p><div className="service-bottom"><span><b>{price(s.price,data.settings.currency)}</b> <span className="muted">/ {s.duration} min</span></span><ArrowUpRight size={21}/></div></a>)}</div></section>
 <section id="book" className="booking-section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">02 / MAKE SOME TIME</div><h2>Your chair is waiting.</h2></div><p>Only Joe’s available times appear here.<br/>Pick one and make it yours.</p></div><BookingFlow data={data} loaded={loaded} refresh={refresh}/></div></section>
 <section id="how" className="wrap how-section"><div><div className="eyebrow">GOOD HAIR, LESS ADMIN</div><h2>Three steps.<br/>One fresh start.</h2></div><div className="steps-list">{[['01','Choose your cut','A tidy-up or the full refresh. You decide.'],['02','Find your opening','Joe adds his hours. You pick the time that fits.'],['03','See you in the chair','Save your confirmation and arrive ready for a fresh cut.']].map(([n,h,p])=><div key={n}><span>{n}</span><div><h3>{h}</h3><p>{p}</p></div></div>)}</div></section>
 <section id="visit" className="wrap visit-section"><div><div className="eyebrow">BEFORE YOU DROP BY</div><h2>A few good details.</h2><p className="location-line"><MapPin size={19}/>{data.settings.location||'Location details coming soon.'}</p><div className="contact-instagram"><span className="eyebrow">LET’S TALK ON INSTAGRAM</span><a className="button primary" href="https://www.instagram.com/joesblendz/" target="_blank" rel="noopener noreferrer"><Instagram size={20}/> @joesblendz <ArrowUpRight size={17}/></a><p>Questions about your cut or appointment? Send Joe a DM.</p></div>{data.settings.contact&&<p className="secondary-contact">Prefer email? <a href={data.settings.contact.includes("@")?"mailto:"+data.settings.contact:undefined}>{data.settings.contact}</a></p>}<span className="timezone-label">All appointments shown in {data.settings.timezone.replace(/_/g,' ')}.</span></div><div className="faq"><details open><summary>When can I book?</summary><p>Joe works by appointment and adds his available hours as he goes. Book up to 90 days ahead, with at least {data.settings.notice} hours’ notice. If there are no times, check back for new openings.</p></details><details><summary>Need to change your plans?</summary><p>Use your private booking link to cancel at least {data.settings.cancellationHours} hours before your appointment, then book a new time. For later changes, <a className="inline-instagram" href="https://www.instagram.com/joesblendz/" target="_blank" rel="noopener noreferrer">DM @joesblendz on Instagram</a>.</p></details><details><summary>How do I pay?</summary><p>Pay Joe at your appointment. There’s no online payment or deposit.</p></details><details><summary>Will I get a confirmation?</summary><p>You’ll get an instant confirmation on screen, a calendar download, and a private booking link. Save the link before leaving; email and text reminders are not enabled.</p></details></div></section>
 </>}
 <footer className="wrap footer"><a className="brand" href="/"><Scissors size={22}/> JOESBLENDZ</a><span>A fresh cut goes a long way.</span><a className="footer-instagram" href="https://www.instagram.com/joesblendz/" target="_blank" rel="noopener noreferrer"><Instagram size={16}/> @joesblendz</a><a href="/admin">Joe’s dashboard <ArrowUpRight size={14}/></a><small>© {new Date().getFullYear()} Joesblendz</small></footer>
 </>;
}
function BookingFlow({data,loaded,refresh}:{data:PublicData;loaded:boolean;refresh:()=>Promise<void>}){
 const [serviceId,setService]=useState('signature'),[day,setDay]=useState(''),[start,setStart]=useState<number|null>(null),[step,setStep]=useState(1),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[booking,setBooking]=useState<Booking|null>(null);
 useEffect(()=>{if(!data.services.some(s=>s.id===serviceId)){setService(data.services[0]?.id||'');setStart(null);setStep(1);}},[data.services,serviceId]);
 const s=data.services.find(s=>s.id===serviceId),z=data.settings.timezone,slots=data.slots[serviceId]||[],days=[...new Set(slots.map(t=>dayKey(t,z)))],times=slots.filter(t=>dayKey(t,z)===day);
 useEffect(()=>{const fn=(e:Event)=>{setService((e as CustomEvent).detail);setStep(1);setStart(null);setDay('');setOffset(0);};window.addEventListener('choose-service',fn);return()=>window.removeEventListener('choose-service',fn);},[]);
 useEffect(()=>{if(!day||!days.includes(day))setDay(days[0]||'');if(start&&!slots.includes(start)){setStart(null);setStep(1);setError('That time is no longer available. Please choose another.');}},[JSON.stringify(slots)]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!s||!start)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const b=await api({action:'book',serviceId:s.id,quotedPrice:s.price,quotedDuration:s.duration,quotedCurrency:data.settings.currency,start,name:f.get('name'),email:f.get('email'),phone:f.get('phone'),note:f.get('note'),website:f.get('website')});setBooking(b);await refresh();}catch(e){setError((e as Error).message);await refresh();}finally{setBusy(false);}}
 if(booking)return <Confirmation b={booking} token={booking.token!}/>;
 return <div className="booking-grid"><div className="booking-panel"><div className="step-tabs"><button className={step===1?'active':''} onClick={()=>setStep(1)}><span>1</span> Service & time</button><button disabled={!start} className={step===2?'active':''} onClick={()=>setStep(2)}><span>2</span> Your details</button><span className="last-step"><span>3</span> You’re booked</span></div>{error&&<p className="notice error" role="alert">{error}</p>}
 {step===1?<><label className="field-label" htmlFor="service">What are we doing today?</label><select id="service" value={serviceId} onChange={e=>{setService(e.target.value);setStart(null);setDay('');setOffset(0);}}>{data.services.map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration} min · {price(s.price,data.settings.currency)}</option>)}</select><div className="date-heading"><h3>Pick your day</h3><div><button className="icon-button" aria-label="Earlier dates" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-5))}><ChevronLeft size={17}/></button><button className="icon-button" aria-label="Later dates" disabled={offset+5>=days.length} onClick={()=>setOffset(offset+5)}><ChevronRight size={17}/></button></div></div>
 {!loaded?<div className="empty-state">Loading available times…</div>:!days.length?<div className="empty-state"><CalendarDays size={30}/><h3>No openings just yet.</h3><p>Joe hasn’t added any available times for this service.<br/>Check back soon for your next fresh cut.</p><button className="text-button" onClick={refresh}>Refresh availability <ArrowRight size={15}/></button></div>:<><div className="date-strip">{days.slice(offset,offset+5).map(d=>{const t=slots.find(t=>dayKey(t,z)===d)!;return <button key={d} aria-pressed={d===day} className={d===day?'date-tile selected':'date-tile'} onClick={()=>{setDay(d);setStart(null);}}><span>{new Intl.DateTimeFormat('en',{timeZone:z,weekday:'short'}).format(t)}</span><b>{new Intl.DateTimeFormat('en',{timeZone:z,day:'numeric'}).format(t)}</b><span>{new Intl.DateTimeFormat('en',{timeZone:z,month:'short'}).format(t)}</span></button>;})}</div><div className="time-heading"><h3>And your time</h3><span>{z.replace(/_/g,' ')}</span></div><div className="time-grid">{times.map(t=><button key={t} aria-pressed={t===start} className={t===start?'time-slot selected':'time-slot'} onClick={()=>{setStart(t);setError('');}}>{time(t,z)}</button>)}</div></>}
 <button className="button primary full" disabled={!start||!s} onClick={()=>setStep(2)}>Continue to your details <ArrowRight size={17}/></button><p className="under-button"><ShieldCheck size={14}/> Your time is reserved when you confirm your booking.</p></>:<form onSubmit={submit}><h3>Let’s make it official.</h3><p className="muted">A few details so Joe knows who’s coming.</p><label>Your name<input required name="name" minLength={2} maxLength={80} autoComplete="name" placeholder="First and last name"/></label><div className="form-row"><label>Email address<input required name="email" type="email" maxLength={180} autoComplete="email" placeholder="you@example.com"/></label><label>Phone number<input required name="phone" type="tel" minLength={7} maxLength={35} autoComplete="tel" placeholder="(555) 123-4567"/></label></div><label>Anything Joe should know? <span className="muted">(optional)</span><textarea name="note" maxLength={500} placeholder="Your style, preferences, or a question…" rows={3}/></label><div className="honeypot" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off"/></div><label className="check-label"><input required type="checkbox"/> I agree to the {data.settings.cancellationHours}-hour cancellation policy. My details will be used to manage this appointment.</label><button className="button primary full" disabled={busy}>{busy?'Reserving your chair…':'Confirm my booking'}<Check size={18}/></button><p className="under-button">Pay at your appointment · No online payment</p></form>}
 </div><aside className="booking-summary"><div className="eyebrow">YOUR NEXT FRESH CUT</div><div className="summary-mark"><Scissors size={34}/></div><h3>{s?.name||'Choose your service'}</h3><p>{s?.description}</p><div className="summary-row"><span><Clock3 size={16}/> Duration</span><b>{s?.duration||'—'} min</b></div><div className="summary-row"><span><CalendarDays size={16}/> When</span><b>{start?<>{date(start,z)}<br/>{time(start,z)}</>:'Your choice'}</b></div><div className="summary-total"><span>Total</span><b>{s?price(s.price,data.settings.currency):'—'}<small>{data.settings.currency}</small></b></div><p className="summary-foot">One chair. Your time.<br/>Let’s make it a good hair day.</p></aside></div>;
}
function Confirmation({b,token}:{b:Booking;token:string}){
 const [copied,setCopied]=useState(false);const url=typeof window==='undefined'?'':location.origin+'/#booking='+encodeURIComponent(token);
 return <div className="confirmation"><div className="success-icon"><CheckCircle2 size={34}/></div><div className="eyebrow">{b.status==='cancelled'?'PLANS CHANGE. WE GET IT.':'IT’S OFFICIAL'}</div><h2>{b.status==='cancelled'?'Appointment cancelled.':'You’re in, '+b.name.split(' ')[0]+'.'}</h2><p>{b.status==='cancelled'?'Your time has been released for someone else.':'Your chair is reserved. See you looking sharp.'}</p><div className="confirmation-details"><b>{b.service_name}</b><span>{date(b.start,b.settings.timezone)} · {time(b.start,b.settings.timezone)}</span><span>{b.settings.timezone} · {price(b.price,b.settings.currency)}</span>{b.settings.location&&<span>{b.settings.location}</span>}</div>{b.status==='confirmed'&&<><div className="actions"><button className="button primary" onClick={()=>calendar(b)}><Download size={17}/> Add to calendar</button><button className="button outline" onClick={async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);}catch{setCopied(false);}}}><Copy size={17}/>{copied?'Link copied':'Copy booking link'}</button></div><label className="save-link">Keep this private link to view or cancel your booking.<input readOnly value={url} onFocus={e=>e.currentTarget.select()}/></label><p className="muted">Save this link now. Email and text confirmations are not enabled.</p><a className="text-button" href={url} onClick={()=>{location.href=url;location.reload();}}>Manage this appointment <ArrowRight size={15}/></a></>}<a className="text-button" href="/">Back to Joesblendz <ArrowUpRight size={15}/></a></div>;
}
function Manage({token,onChange}:{token:string;onChange:()=>Promise<void>}){
 const [b,setB]=useState<Booking|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 useEffect(()=>{api({action:'manage',token}).then(setB).catch(e=>setError(e.message));},[token]);
 async function cancel(){setBusy(true);try{setB(await api({action:'cancel',token}));setConfirm(false);await onChange();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="wrap manage">{error&&<p role="alert" className="notice error">{error}</p>}{b?<><Confirmation b={b} token={token}/>{b.status==='confirmed'&&<div className="cancel-box"><h3>Need a different time?</h3><p>Cancel here, then book a new appointment. Online cancellation closes {b.settings.cancellationHours} hours before your visit.{b.settings.contact&&' For help: '+b.settings.contact}</p>{confirm?<div className="actions"><button className="button danger" disabled={busy} onClick={cancel}>{busy?'Cancelling…':'Yes, cancel appointment'}</button><button className="button outline" onClick={()=>setConfirm(false)}>Keep my appointment</button></div>:<button className="text-button danger-text" onClick={()=>setConfirm(true)}>Cancel appointment</button>}</div>}</>:!error&&<p>Finding your appointment…</p>}</main>;
}
function Admin({onChange}:{onChange:()=>Promise<void>}){
 const [data,setData]=useState<AdminData|null>(null),[tab,setTab]=useState('schedule'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('upcoming'),[pending,setPending]=useState<{action:string;id:string}|null>(null),[edit,setEdit]=useState<Service|null>(null);
 const load=useCallback(async()=>{try{setData(await api(undefined,'admin'));setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{load();},[load]);
 async function act(body:unknown,message:string){setBusy(true);setError('');setNotice('');try{await api(body);setNotice(message);await load();await onChange();setPending(null);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 if(!data)return <main className="wrap admin-login"><ShieldCheck size={38}/><div className="eyebrow">JUST FOR JOE</div><h1>Your chair.<br/>Your schedule.</h1><p>Sign in to set your hours and manage your appointments.</p>{error&&<p className="notice" role="alert">{error}</p>}<OwnerLogin onSignedIn={load}/><p className="muted">Use your private owner password.</p></main>;
 const z=data.settings.timezone,upcoming=data.bookings.filter(b=>b.status==='confirmed'&&b.end>Date.now()).sort((a,b)=>a.start-b.start);
 return <main className="wrap admin"><div className="admin-heading"><div><div className="eyebrow">JOE’S DASHBOARD</div><h1>Make room for a good cut.</h1><p>Set your hours. We’ll handle the open times.</p></div><button className="text-button" onClick={async()=>{try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});if(!r.ok)throw new Error("Unable to sign out. Please try again.");location.assign("/admin");}catch(e){setError((e as Error).message);}}}><LogOut size={16}/> Sign out</button></div><div className="stat-grid"><div><span>Upcoming appointments</span><b>{upcoming.length}</b></div><div><span>Available work windows</span><b>{data.availability.length}</b></div><div><span>Scheduled chair time</span><b>{upcoming.reduce((n,b)=>n+(b.end-b.start)/60000,0)} min</b></div></div><div className="admin-tabs">{[['schedule','Availability'],['bookings','Appointments'],['services','Services'],['settings','Settings']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setNotice('');setError('');}}>{label}</button>)}</div>{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice success" role="status"><Check size={17}/>{notice}</p>}{pending&&<div className="notice confirm-bar"><span>{pending.action==='cancelAdmin'?'Cancel this appointment? Its time becomes bookable again. Please notify the client yourself.':'Remove this work window? Unbooked times in it will disappear.'}</span><button className="button danger small" disabled={busy} onClick={()=>act(pending,'Done.')}>Confirm</button><button className="button outline small" onClick={()=>setPending(null)}>Keep it</button></div>}
 {tab==='schedule'&&<div className="admin-columns"><section className="admin-card"><h2>Add your availability</h2><p>Choose a day and the hours you want to work. Clients can only book inside these windows.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act({action:'availability',date:f.get('date'),from:f.get('from'),to:f.get('to')},'Availability added. Clients can now book these hours.');}}><label>Date<input required name="date" type="date" min={dayKey(Date.now(),z)}/></label><div className="form-row"><label>From<input required name="from" type="time" step={900} defaultValue="10:00"/></label><label>Until<input required name="to" type="time" step={900} defaultValue="17:00"/></label></div><p className="muted">Times in {z}. Add separate windows for breaks or split shifts.</p><button className="button primary full" disabled={busy}><Plus size={17}/> Add available hours</button></form></section><section className="admin-card"><h2>Your work windows</h2><p>Booked time is automatically removed from the client’s choices.</p>{!data.availability.length?<div className="empty-state"><CalendarDays/><h3>A blank slate.</h3><p>Add your first work window to open your chair.</p></div>:data.availability.map(w=><div key={w.id} className="window-row"><div><b>{date(w.start,z)}</b><span>{time(w.start,z)} – {time(w.end,z)}</span></div><button className="icon-button danger-text" aria-label={'Remove '+date(w.start,z)} onClick={()=>setPending({action:'removeAvailability',id:w.id})}><Trash2 size={18}/></button></div>)}</section></div>}
 {tab==='bookings'&&<section className="admin-card"><div className="section-heading"><div><h2>Your appointments</h2><p>All times in {z}. Contact clients directly about changes.</p></div><select aria-label="Filter appointments" value={filter} onChange={e=>setFilter(e.target.value)}><option value="upcoming">Upcoming</option><option value="all">All appointments</option><option value="cancelled">Cancelled</option></select></div><div className="appointments">{(filter==='upcoming'?upcoming:filter==='cancelled'?data.bookings.filter(b=>b.status==='cancelled'):data.bookings).map(b=><article className="appointment" key={b.id}><div className="appointment-date"><b>{new Intl.DateTimeFormat('en',{timeZone:z,day:'numeric'}).format(b.start)}</b><span>{new Intl.DateTimeFormat('en',{timeZone:z,month:'short'}).format(b.start)}</span></div><div><h3>{b.name}<span className={'badge '+b.status}>{b.status}</span></h3><p>{b.service_name} · {time(b.start,z)}–{time(b.end,z)} · {date(b.start,z)} · {price(b.price,b.currency||data.settings.currency)}</p><p><a href={'mailto:'+b.email}>{b.email}</a> · <a href={'tel:'+b.phone}>{b.phone}</a></p>{b.note&&<p className="client-note">{b.note}</p>}</div>{b.status==='confirmed'&&<button className="text-button danger-text" onClick={()=>setPending({action:'cancelAdmin',id:b.id})}>Cancel</button>}</article>)}{!(filter==='upcoming'?upcoming:filter==='cancelled'?data.bookings.filter(b=>b.status==='cancelled'):data.bookings).length&&<div className="empty-state"><CalendarDays/><h3>No appointments here yet.</h3><p>Your clients’ bookings will appear here.</p></div>}</div></section>}
 {tab==='services'&&<section className="admin-card"><div className="section-heading"><div><h2>Your menu</h2><p>Changes apply to new bookings. Existing appointment details stay as booked.</p></div><button className="button primary small" onClick={()=>setEdit({id:'',name:'',description:'',price:3000,duration:30,active:1})}><Plus size={16}/> Add service</button></div>{!data.services.length&&<div className="empty-state"><p>Load the Joesblendz menu, then customize it.</p><button className="button outline" disabled={busy} onClick={()=>act({action:'initialize'},'Joesblendz services added. Edit them below.')}>Add Joesblendz menu</button></div>}{data.services.map(s=><div className="window-row" key={s.id}><div><b>{s.name} {!s.active&&<span className="badge">Hidden</span>}</b><span>{s.duration} min · {price(s.price,data.settings.currency)} · {s.description}</span></div><button className="text-button" onClick={()=>setEdit(s)}>Edit <Settings2 size={15}/></button></div>)}
 {edit&&<form className="edit-service" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await act({action:'service',service:{id:edit.id,name:f.get('name'),description:f.get('description'),duration:Number(f.get('duration')),price:Math.round(Number(f.get('price'))*100),active:f.get('active')?1:0}},'Service saved.'))setEdit(null);}} key={edit.id}><h3>{edit.id?'Edit service':'New service'}</h3><label>Service name<input name="name" required maxLength={70} defaultValue={edit.name}/></label><label>Description<input name="description" maxLength={180} defaultValue={edit.description}/></label><div className="form-row"><label>Duration (minutes)<input name="duration" type="number" required min={15} max={240} step={15} defaultValue={edit.duration}/></label><label>Price ({data.settings.currency})<input name="price" type="number" required min={0} max={1000} step="0.01" defaultValue={edit.price/100}/></label></div><label className="check-label"><input type="checkbox" name="active" defaultChecked={!!edit.active}/> Visible to clients</label><div className="actions"><button className="button primary" disabled={busy}>Save service</button><button type="button" className="button outline" onClick={()=>setEdit(null)}>Discard</button></div></form>}</section>}
 {tab==='settings'&&<section className="admin-card settings-card"><h2>The details that matter.</h2><p>Confirm your business details before you launch.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:'settings',settings:{location:f.get('location'),contact:f.get('contact'),timezone:f.get('timezone'),currency:f.get('currency'),notice:Number(f.get('notice')),cancellationHours:Number(f.get('cancellationHours')),sample:!!f.get('sample')}},'Settings saved.');}}><label>Appointment location<input name="location" maxLength={250} placeholder="Studio name and street address" defaultValue={data.settings.location}/></label><label>Public contact details<input name="contact" maxLength={180} placeholder="Phone number or email for booking questions" defaultValue={data.settings.contact}/></label><div className="form-row"><label>Time zone<input required name="timezone" defaultValue={z} placeholder="America/Toronto"/></label><label>Currency<select name="currency" defaultValue={data.settings.currency}>{['CAD','USD','EUR','GBP'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="muted">Changing the time zone changes how existing appointments are displayed; it does not move them.</p><div className="form-row"><label>Minimum booking notice (hours)<input required name="notice" type="number" min={0} max={168} defaultValue={data.settings.notice}/></label><label>Cancellation notice (hours)<input required name="cancellationHours" type="number" min={0} max={168} defaultValue={data.settings.cancellationHours}/></label></div><label className="check-label"><input type="checkbox" name="sample" defaultChecked={data.settings.sample}/> Show “sample menu” label while preparing the site</label><button className="button primary" disabled={busy}>Save settings <Check size={17}/></button></form></section>}
 </main>;
}



function OwnerLogin({onSignedIn}:{onSignedIn:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="owner-login" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',password:f.get('password')})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);await onSignedIn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>Owner password<input name="password" type="password" required autoComplete="current-password" maxLength={256}/></label>{error&&<p role="alert" className="notice error">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Signing in…':'Sign in to dashboard'}<ArrowRight size={17}/></button><p className="muted">Lost the password? Reset ADMIN_PASSWORD in your Cloudflare account.</p></form>;}
